### ISSUE TITLE
Alt Gr + 4 should produce { on French keyboard, it jumps to 4th tab

### ISSUE THREAD

**Issue by AlGrenadine** [trollixx/qtcreator-tabbededitor-plugin#18] opened 2015-06-05 07:11 UTC
Alt Gr + 4 should produce { on French keyboard, it jumps to 4th tab

**Comment by trollixx** [comment] 2015-06-07 05:51
Duplicate of #17, I hope to fix it soon.

**Closed by trollixx** 2015-06-07 05:51 UTC
